@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
title RDCU pour redémarrerJeu
participant ":JeuDeDes" as c
->c : redemarrerJeu()
note right : selon Contrôleur\n(JeuDeDés est \nl'objet racine)
participant "Map<String, Joueur>" as jm
c -> jm : clear()
note right : selon Expert
@enduml